language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1

before_script:
  - composer install
  - chmod 777 install.sh

script:
  - mkdir -p build/logs 
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml test/
  - sh install.sh
